image: ghcr.io/llm-d/llm-d-inference-sim:v0.7.1
logLevel: INFO
scenarioUrl: http://example.com
targetRps: 20
durationSeconds: 60
concurrentUsers: 5
warmupSeconds: 10
apiType: completion
streaming: false
serverType: vllm
modelName: HuggingFaceTB/SmolLM2-135M-Instruct
dataType: synthetic
loadIntervalSeconds: 1.0
workerMaxConcurrency: 100
workerMaxTCPConnections: 2500
# Inference-perf config reference:
# https://github.com/kubernetes-sigs/inference-perf/blob/main/docs/config.md
inputDistribution:
  min: 16
  max: 256
  mean: 64
  std_dev: 16
  total_count: 500
outputDistribution:
  min: 16
  max: 128
  mean: 48
  std_dev: 12
  total_count: 500
activeDeadlineSeconds: 240
backoffLimit: 0
ttlSecondsAfterFinished: 300
imagePullPolicy: IfNotPresent