apiVersion: v1
kind: ConfigMap
metadata:
  name: inference-perf-config
data:
  config.yml: |
    load:
      type: constant
      stages:
      - rate: {{ .Values.targetRps }}
        duration: {{ .Values.durationSeconds }}
      num_workers: {{ .Values.concurrentUsers }}
    api:
      type: {{ .Values.apiType | quote }}
      streaming: {{ .Values.streaming }}
    server:
      type: {{ .Values.serverType | quote }}
      model_name: {{ .Values.modelName | quote }}
      base_url: {{ .Values.scenarioUrl | quote }}
    data:
      type: {{ .Values.dataType | quote }}
      {{- if eq .Values.dataType "synthetic" }}
      input_distribution:
        min: 10
        max: 1024
        mean: 256
        std_dev: 100
      output_distribution:
        min: 10
        max: 1024
        mean: 256
        std_dev: 100
      {{- end }}
    report:
      request_lifecycle:
        summary: true
        per_stage: true
        per_request: false